# Generated by Django 5.2.3 on 2025-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='borrows',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=1),
        ),
    ]
